### ISSUE TITLE
Cannot use on Ubuntu 20.04 (building not possible)

### ISSUE THREAD

**Issue by Paderman** [simos/keyboardlayouteditor#39]
I can't use the editor in new version of Ubuntu.
I tried to build and similar, but nothing works, I can only delete all files of it :sob: 

If you have an idea to use this editor on newer versions of Ubuntu, please let me (us) know.

Better it would exist an AppImage :smile: because that image contains all necessary files and so.

**Comment by alanmels** [comment]
I do confirm it's not building with pip3 (earlier versions of pip won't work on Ubuntu 20.04), giving:

sudo pip3 install http://www.antlr3.org/download/Python/antlr_python_runtime-3.1.2.tar.gz
Collecting http://www.antlr3.org/download/Python/antlr_python_runtime-3.1.2.tar.gz
  Downloading http://www.antlr3.org/download/Python/antlr_python_runtime-3.1.2.tar.gz (67 kB)
     |████████████████████████████████| 67 kB 370 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-63chk88f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-63chk88f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-63chk88f/pip-egg-info
         cwd: /tmp/pip-req-build-63chk88f/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-63chk88f/setup.py", line 49
        except OSError, exc:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by HabibSlim** [comment]
Probably comes in too late, but you should install with pip2 instead of pip3. This repository is 13 years old guys

**Comment by Kaboom4224** [comment]
the pip manpage tells me "pip" is used for python2 and "pip3" is used for python3 on debian

**Comment by nickvsnetworking** [comment]
Very late to the party here, but you can install PyGTK for Python 2.7 from the old repos
```
wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb
sudo apt-get install ./python-gtk2_2.24.0-5.1ubuntu2_amd64.deb
```

The program then works in Ubuntu 20.04.

**Comment by SebastianGrans** [comment]
I'm running 20.04 and `pip2` was not installed, nor available in APT.
To install `pip2`, run the following ([source](https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/)):

```
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
python2 get-pip.py
``` 

I got it running, but it doesn't work. I'll look into it when I have some time... 
![Screenshot from 2021-12-17 17-38-56](https://user-images.githubusercontent.com/10030015/146578051-12389bef-0901-4d7e-a71d-a070d06c297a.png)
